---
title: "Sustainability Roles"
author: "Arjun Kumar"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
```

```{r, echo=FALSE}
#laod libraries
library(igraph)
library(tidyverse)
library(quanteda)
library(visNetwork)
```

```{r, echo=FALSE}


roles_network <- function(sector, coocterm, ncoocs){
setwd("~/Documents/GitHub/linkedin_scraper")
roles_df = read.csv(paste(sector, "_roles.csv", sep = ""))
roles_corp = corpus(roles_df, text_field = 'role')
summary(roles_corp, 5)

roles_toks = tokens(roles_corp, 
                    remove_punct = TRUE,
                    remove_symbols = TRUE,
                    remove_numbers = TRUE,
                    remove_url = TRUE,
                    remove_separators = TRUE)

roles_toks %>% head()
roles_toks = roles_toks %>% tokens_remove(c(stopwords("english"), 'standard', "chartered", "bnp", "paribas", "jpmorgan", "chase", "j.p",
                                            "CO", "w", "I", "morgan",
                                            "bnpp", "jp", "citi", "hsbc",
                                            "microsoft", "google",
                                            "amazon", "apple", "meta",
                                            "aws", "dbs"))

roles_toks = roles_toks %>% tokens_replace("manager-", "manager")

min_freq <- 5

# Create DTM, prune vocabulary and set binary values for presence/absence of types
roles_dfm <- roles_toks %>%
             dfm() %>% 
             dfm_trim(min_docfreq = min_freq) %>%                                        dfm_weight("boolean")

roles_dfm

roles_cc = t(roles_dfm) %*% roles_dfm
roles_cc[1:5, 1:5]

cooct <- coocterm
k <- nrow(roles_dfm)
ki <- sum(roles_dfm[, cooct])
kj <- colSums(roles_dfm)
names(kj) <- colnames(roles_dfm)
kij <- roles_cc[cooct, ]

# Read in the source code for the co-occurrence calculation
source("calcCoocStats.R")
#ncoocs
#cooct <- cterm

coocs <- calcCoocStats(cooct, roles_dfm, measure="DICE")
# Display the ncoocs main terms
#print(coocs[1:ncoocs])

resultGraph <- data.frame(from = character(), to = character(), sig = numeric(0))

# The structure of the temporary graph object is equal to that of the resultGraph
tmpGraph <- data.frame(from = character(), to = character(), sig = numeric(0))

# Fill the data.frame to produce the correct number of lines
tmpGraph[1:ncoocs, 3] <- coocs[1:ncoocs]
# Entry of the search word into the first column in all lines
tmpGraph[, 1] <- cooct
# Entry of the co-occurrences into the second column of the respective line
tmpGraph[, 2] <- names(coocs)[1:ncoocs]
# Set the significances
tmpGraph[, 3] <- coocs[1:ncoocs]

# Attach the triples to resultGraph
resultGraph <- rbind(resultGraph, tmpGraph)

# Iteration over the most significant ncoocs co-occurrences of the search term
for (i in 1:ncoocs){
  
  # Calling up the co-occurrence calculation for term i from the search words co-occurrences
  newcooct <- names(coocs)[i]
  coocs2 <- calcCoocStats(newcooct, roles_dfm, measure="DICE")
  
  #print the co-occurrences
  #coocs2[1:10]
  
  # Structure of the temporary graph object
  tmpGraph <- data.frame(from = character(), to = character(), sig = numeric(0))
  tmpGraph[1:ncoocs, 3] <- coocs2[1:ncoocs]
  tmpGraph[, 1] <- newcooct
  tmpGraph[, 2] <- names(coocs2)[1:ncoocs]
  tmpGraph[, 3] <- coocs2[1:ncoocs]
  
  #Append the result to the result graph
  resultGraph <- rbind(resultGraph, tmpGraph[2:length(tmpGraph[, 1]), ])
}


# set seed for graph plot
set.seed(1)

# Create the graph object as undirected graph
graphNetwork <- graph.data.frame(resultGraph, directed = F)

# Identification of all nodes with less than 2 edges
verticesToRemove <- V(graphNetwork)[degree(graphNetwork) < 3]
# These edges are removed from the graph
graphNetwork <- delete.vertices(graphNetwork, verticesToRemove) 

# Assign colors to nodes (search term blue, others orange)
V(graphNetwork)$color <- adjustcolor(ifelse(V(graphNetwork)$name == cooct, 'darkgreen', 'grey'), alpha.f = .5) 


# Set edge colors
E(graphNetwork)$color <- adjustcolor("DarkGray", alpha.f = .4)
# scale significance between 1 and 10 for edge width
E(graphNetwork)$width <- scales::rescale(E(graphNetwork)$sig, to = c(1, 10))

# Set edges with radius
E(graphNetwork)$curved <- 0.05
# Size the nodes by their degree of networking (scaled between 5 and 15)
V(graphNetwork)$size <- scales::rescale(log(degree(graphNetwork)), to = c(5, 15))

# Define the frame and spacing for the plot
par(mai=c(0,0,1,0)) 

# Final Plot
plot(
  graphNetwork,             
  layout = layout.fruchterman.reingold, # Force Directed Layout 
  main = paste(cooct, 'graph'),
  vertex.label.family = "sans",
  vertex.label.cex = 0.8,
  vertex.shape = "circle",
  vertex.label.dist = 0,          # Labels of the nodes moved slightly
  vertex.label.degree=pi/2,
  vertex.frame.color = adjustcolor("white", alpha.f = .2),
  vertex.label.color = 'black',     # Color of node names
  vertex.label.font = 2,            # Font of node names
  vertex.label = V(graphNetwork)$name,      # node names
  vertex.label.cex = 2 # font size of node names
)

coocs_df = data.frame(coocs)
colnames(coocs_df)[1] = 'dice'
return(coocs_df)

}

#return dataframe too

```

```{r, fig.height=10, fig.width=10, echo=FALSE}


bankcoocs_df = roles_network('bank', 'lead', 15)
#bankcoocs_df = roles_network('bank', 'cloud', 5)
bankcoocs_df = roles_network('bank', 'sustainability', 15)

```


```{r, fig.height=6, fig.width=12, echo=FALSE}
bankcoocs_df['role'] = row.names(bankcoocs_df)
print(head(bankcoocs_df, 20))

head(bankcoocs_df, 20) %>% ggplot(aes(y = reorder(role, dice), x = dice)) +
   geom_point(color = 'deepskyblue') +
   geom_segment(aes(x = 0, y = role, xend = dice, yend = role)) +
   xlab('dice coefficient') + ylab('sustainability roles')  +
   ggtitle('Banks') + geom_text(aes(label = round(dice, 2)), hjust=-0.3, size = 3) +
   theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
         panel.background = element_blank(), axis.line.y = element_line('black')) + 
  theme(axis.line.x = element_blank(), axis.ticks.x = element_blank(), axis.text.x = element_blank(), axis.text.y=element_text(size=12), axis.title=element_text(size=14))
```



```{r,fig.height=10, fig.width=10, echo=FALSE}

techcoocs_df = roles_network('tech', 'lead', 15)
techcoocs_df = roles_network('tech', 'cloud', 15)
techcoocs_df = roles_network('tech', 'sustainability', 15)

```


```{r,fig.height=6, fig.width=12, echo=FALSE}
techcoocs_df['role'] = row.names(techcoocs_df)
print(head(techcoocs_df, 20))

head(techcoocs_df, 20) %>% ggplot(aes(y = reorder(role, dice), x = dice)) +
   geom_point(color = 'firebrick') +
   geom_segment(aes(x = 0, y = role, xend = dice, yend = role)) +
   xlab('dice coefficient') + ylab('sustainability roles')  +
   ggtitle('Tech') + geom_text(aes(label = round(dice, 2)), hjust=-0.3, size = 3) +
   theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
         panel.background = element_blank(), axis.line.y = element_line('black')) + 
  theme(axis.line.x = element_blank(), axis.ticks.x = element_blank(), axis.text.x = element_blank(), axis.text.y=element_text(size=12), axis.title=element_text(size=14))


```



```{r, fig.height=10, fig.width=10, echo=FALSE}

dbscoocs_df = roles_network('dbs', 'sustainability', 15)
#dbscoocs_df = roles_network('dbs', 'lead', 15)
dbscoocs_df = roles_network('dbs', 'head', 15)


```
